### ISSUE TITLE
フロントエンドへの反映方法に差異がある

### ISSUE THREAD

**Issue by erinanire** [diverta/front_nuxt_corporate#14]
【不具合内容】
フロントエンドへのコンテンツ反映方法に差異があります。
例えばニュース一覧画面は即時反映ですが、詳細画面への反映はビルドが必要です。

【修正方法】
https://github.com/diverta/front_nuxt_corporate/blob/main/nuxt.config.ts#L4
// ssr: true,
の部分を
ssr: false,
に変更いただくとCSRになります。
手元で一通り動作確認しておりますが、確認の上修正いただけると嬉しいです。

**Comment by KentaKatoh** [comment]
@HisashiHasebe アーカイブを作るのにマスター使ってると思うのですが、マスター使うのはちょっとテンプレート的にはイマイチかなと。。何かリンクを付与したのであれば、カテゴリで自動でやれると思うのでそっちの方がいい気がする。

**Comment by takel-shiba** [comment]
@VortexExpansion 
Could you change SSG -> CSR
```
ssr: false,
```
and please check call API every case

After that make PR with mention to @yabe-diverta 

アーカイブの件はCSR後に別Issueで検討・対応 @HisashiHasebe
