### ISSUE TITLE
Unexpected date input

### ISSUE THREAD

**Issue by yabe-diverta** [diverta/front_nuxt_corporate#18]
[Here](https://github.com/diverta/front_nuxt_corporate/blob/main/pages/contact/index.vue#L149) will cause invalid date issue.
e.g. ) 2000-02-31

**Comment by yabe-diverta** [comment]
The static options in select input would cause unexpected date selection (e.g. selecting "02" month should have limited dates up to 28).
We should make calendar component for date selection, or manage all inputs in date-related ones, and I think calendar is better than the latter.

**Comment by VortexExpansion** [comment]
@yabe-diverta san 

I implemented [vue datepicker](https://vue3datepicker.com/installation/)
Please review.
