### ISSUE TITLE
Sending files from the form

### ISSUE THREAD

**Issue by HisashiHasebe** [diverta/front_nuxt_corporate#20]
Currently not working.

https://diverta.gyazo.com/c996b9cac2fb11baeee38255f1b7e57c

**Comment by VortexExpansion** [comment]
@HisashiHasebe san 
Fixed now. Please review. 

I think the main reason for failing of API `/rcms-api/1/upload` was change in API response value
from `response.data.file_id` to `response.file_id`

**Comment by HisashiHasebe** [comment]
@VortexExpansion 
Thank you! confirmed.
