### ISSUE TITLE
会員限定ページ（詳細）でリロードまたはURLに直接アクセスするとトップへリダイレクトされる

### ISSUE THREAD

**Issue by nakasoneyoshihiro** [diverta/front_nuxt_corporate#4]
htmlファイルの実態がない場合リダイレクトされているようです。
kuroco_front.jsonのrewriteで修正できると思います。

**Comment by VortexExpansion** [comment]
Not reproducible anymore. I think this issue can be closed now.

@yabe-diverta san

**Comment by yabe-diverta** [comment]
Checked as well.
No issues found now, close.
