### ISSUE TITLE
Is there an appropriate SSG method for a large number of pages that require static generation?

### ISSUE THREAD

**Issue by yhirochick** [diverta/front_nuxt_corporate#6]
In Nuxt2, the generate property in nuxt.config.js could handle payloads via asyncData for each detail page as needed.
Nuxt3 also has SSG functionality, but it seems that it is no longer possible to pass payloads to each detail page individually.
Is there any alternative?

We would like to reduce the number of requests and the time required to generate SSG by making one request at build time (split request if necessary), rather than having the request made for the number of pages.

**Comment by HisashiHasebe** [comment]
@yhirochick 
ローカルで試してみたのですが、うまく確認できませんでした。

もしかすると、ビルド時に動作するのかもしれませんが、ローカルで容易に確認できない状態や、build.ymlはKuroco管理画面のサンプル通りで動くように調整しておりますので、こちらが一致しない状態になることは、テンプレートサイトとして適していません。

リクエスト数の削減はテンプレートではなく、クローン後の個々のプロジェクトで必要に応じてご対応をお願いします。
以下のFAQがございますので、こちらのNuxt3版の作成を検討いたします。
[Nuxt.jsのSSGで、ページの生成時にAPIリクエストを減らす方法はありますか？](https://kuroco.app/ja/docs/faq/can-i-use-nuxt-js-ssg-to-reduce-api-calls/)

**Comment by yhirochick** [comment]
@HisashiHasebe 
申し訳ありません。こちらで別途用意していたKurocoFrontでしか確認しておりませんでした。
テンプレート改修の方針について承知しました。

Nuxt3のSSGは以下の記事の方法があるようでしたので共有いたします。
https://zenn.dev/kon_karin/articles/0e514dea329044
Github：https://github.com/konkarin/nuxt3-ssg-dynamic-routing

以下にForkしてkurocoの場合でも検証してます。
https://github.com/yhirochick/nuxt3-ssg-dynamic-routing/tree/kuroco_ssg_test

分かっている問題としては、

- payload extractionが実験的な機能のため今後変更される可能性がある。
- generateした際に各ページに_payload.jsonが作られるが全記事の情報が含まれてしまい容量が大きくなってしまう。

があります。当初のIssue、PullRequestでは上記の問題を解決したい意図がありました。
説明が不足しており申し訳ありません。
また、英語で投稿したのはどなたでもIssueの内容を確認出来るかなと思った次第です。
お手数おかけしてしまいすみませんでした。


今後Nuxt3でのリクエスト数を減らすための方法ご検討いただけるとのこと、ありがとうございます。
何かしら上記の情報が参考になれば幸いです。
よろしくお願いします。
